platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.15.0'
pod 'Alamofire', '~> 3.0'
pod 'Kingfisher', '~> 1.6'
pod 'HanekeSwift'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SQLite.swift',
git: 'https://github.com/stephencelis/SQLite.swift.git'
pod 'JSONModel', '~> 1.1.2'
